from __future__ import annotations

import argparse
import json
import zipfile
from pathlib import Path


REPORT_PREFIX = "Report/definition/"
THEME_PREFIX = "Report/StaticResources/"


def extract_pbix(pbix: Path, output_root: Path, project_name: str) -> None:
    report_dir = output_root / f"{project_name}.Report"
    definition_dir = report_dir / "definition"
    static_dir = report_dir / "StaticResources"

    report_dir.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(pbix, "r") as archive:
        names = archive.namelist()

        if not any(name.startswith(REPORT_PREFIX) for name in names):
            raise RuntimeError("The PBIX does not contain an embedded PBIR definition.")

        for name in names:
            if name.startswith(REPORT_PREFIX) and not name.endswith("/"):
                relative = Path(name[len(REPORT_PREFIX):])
                target = definition_dir / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(archive.read(name))

            elif name.startswith(THEME_PREFIX) and not name.endswith("/"):
                relative = Path(name[len(THEME_PREFIX):])
                target = static_dir / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(archive.read(name))

        if "DiagramLayout" in names:
            raw = archive.read("DiagramLayout")
            text = raw.decode("utf-16-le")
            parsed = json.loads(text)
            (report_dir / "semanticModelDiagramLayout.json").write_text(
                json.dumps(parsed, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )

    definition_pbir = {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definitionProperties/2.0.0/schema.json",
        "version": "4.0",
        "datasetReference": {
            "byPath": {
                "path": f"../{project_name}.SemanticModel"
            }
        },
    }
    (report_dir / "definition.pbir").write_text(
        json.dumps(definition_pbir, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    pbip = {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/pbip/pbipProperties/1.0.0/schema.json",
        "version": "1.0",
        "artifacts": [
            {
                "report": {
                    "path": f"{project_name}.Report"
                }
            }
        ],
        "settings": {
            "enableAutoRecovery": True
        },
    }
    (output_root / f"{project_name}.pbip").write_text(
        json.dumps(pbip, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    print(f"PBIR report extracted to: {report_dir}")
    print("Semantic model TMDL is NOT generated by this script.")
    print("Use Power BI Desktop Save As PBIP to generate/validate the SemanticModel folder.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract embedded PBIR report definition from a modern PBIX."
    )
    parser.add_argument("pbix", type=Path, help="Path to source .pbix")
    parser.add_argument("--output", type=Path, default=Path("src"))
    parser.add_argument("--name", default="pnl_Leads_MKT")
    args = parser.parse_args()

    extract_pbix(args.pbix.resolve(), args.output.resolve(), args.name)


if __name__ == "__main__":
    main()
